title: orca.pet
description: Socram's website
url: https://orca.pet
repository: socram8888/orca.pet
author: Marcos Del Sol Vives
twitter:
    username: Socramite

theme: jekyll-theme-cayman
timezone: Europe/Madrid
lang: en-US

plugins:
  - jekyll-default-layout
  - jekyll-last-modified-at
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-render-order
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-responsive-image

keep_files:
  - notonmyshift/abp.txt
  - notonmyshift/domains.txt
  - notonmyshift/hosts.txt
  - shared/

exclude:
  - /assets/images/secretbg.7z
  - /commit.bat
  - /commit.sh
  - /devserver.bat
  - /devserver.sh
  - /Gemfile
  - /Gemfile.lock
  - /node_modules/
  - /README.md
  - /vendor/

responsive_image:
    template: _includes/responsive-image.html
    sizes:
      - width: 800
        quality: 90
      - width: 1920
        quality: 80
    auto_rotate: true
    strip: true
    output_path_format: assets/resized/%{width}/%{basename}
