name: Website CI

on:
    push:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
                # Clone all history so timestamps are accurate
                fetch-depth: 0

          - name: Setup cache
            uses: actions/cache@v2
            with:
                path: vendor/bundle
                key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
                restore-keys: |
                    ${{ runner.os }}-gems-

          - name: Set up Ruby
            uses: ruby/setup-ruby@v1.52.0
            with:
                ruby-version: 2.5

          - name: Install Ruby dependencies
            run: |
                bundle config path vendor/bundle
                bundle install

          - name: Build Jekyll
            run: JEKYLL_ENV=production bundle exec jekyll build

          - name: Publish to Google Firebase
            uses: FirebaseExtended/action-hosting-deploy@v0
            with:
                repoToken: '${{ secrets.GITHUB_TOKEN }}'
                firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ORCA_PET }}'
                channelId: live
                projectId: orca-pet
                target: orca-pet
            env:
                FIREBASE_CLI_PREVIEWS: hostingchannels
